### ISSUE TITLE
White icon in the VAB/SPH

### ISSUE THREAD

**Issue by skalou** [linuxgurugamer/EditorExtensionsRedux#1]
hi,
I had a white icon in the toolbar until i rename the folder in gamedata just "EditorExtensions" instead of "EditorExtensionsRedux"

**Comment by linuxgurugamer** [comment]
Thank you
I know the problem and a fix will be uploaded shortly

**Comment by linuxgurugamer** [comment]
Fixed and updated

**Comment by skalou** [comment]
great ;)
