### ISSUE TITLE
Feature request: arbitrary part snap

### ISSUE THREAD

**Issue by henrybauer** [linuxgurugamer/EditorExtensionsRedux#12]
EE currently allows to you do vertical and horizontal snap.

This request is to also allow snapping to the height of an arbitrary part.  For example, lining up landing legs that are not in symmetry:

![m1ohhnx](https://cloud.githubusercontent.com/assets/5103358/17222389/b17203b4-5500-11e6-9bba-462f36370ff9.png)

**Comment by linuxgurugamer** [comment]
Added in 1.2
