### ISSUE TITLE
Ghost parts cannot have the root changed.

### ISSUE THREAD

**Issue by MrDrummer** [linuxgurugamer/EditorExtensionsRedux#13]
![editor bug installed](https://cloud.githubusercontent.com/assets/10013572/17738635/0425501e-648a-11e6-9b00-56d8f19f645a.png)
![editor bug uninstalled](https://cloud.githubusercontent.com/assets/10013572/17738636/043db064-648a-11e6-8530-b6bd36b12b1b.png)

Pretty "simple" bug. In vanilla, one can use the re-root functionality to re-root a ghost with multiple parts.

This can be seen in the second screenshot.

Usually, you press 4, select the object you want to re-root, either the main craft, or a ghost and then the second click is the new part to re-root.

With this mod, you press 4 and it defaults to the main craft.

I would imagine whoever created this functionality did not understand the need for two clicks, but it makes complete sense. 1st click, which group of parts to re-root, 2nd to select which part of that selection to re-root to.

I made a fresh save just to test this, so it was tested with complete stock vs just this mod.

I don't think there is much more detail i can provide.

**Comment by linuxgurugamer** [comment]
Fixed in 1.2 release
