### ISSUE TITLE
Prevent EER from reacting to keyboard input when in a "text box"...

### ISSUE THREAD

**Issue by Galenmacil** [linuxgurugamer/EditorExtensionsRedux#17]
...like the search part bar or the ship name/description box. Not really a bug but a possible future quality of life improvement.

**Comment by linuxgurugamer** [comment]
It's a KSP bug

**Comment by sick13** [comment]
Pressing "F" in VAB gets this

NullReferenceException: Object reference not set to an instance of an object
	EditorExtensionsRedux.NoOffsetBehaviour.FreeOffsetBehaviour.LateUpdate ()

is it the same Bug or....?

**Comment by linuxgurugamer** [comment]
No.
I assume you have the latest version?

**Comment by sick13** [comment]
Yes i do, ill be back with more info will test it on stock also, maybe there is a mod conflict.

**Comment by linuxgurugamer** [comment]
Please send me the Output_log.txt, it has more info
Thanks

**Comment by linuxgurugamer** [comment]
Ummm, do you have a part selected at the time you press the F key?

**Comment by sick13** [comment]
No part in the Vab, with part in Vab (selected or not,placed or not) witch every combination always throws that Nullref.

**Comment by linuxgurugamer** [comment]
To summarize:

In the VAB, it happens whether or not a part is selected.
Also, it doesn't seem to matter whether a part is placed or not

Assuming this is correct, I'll look into it this evening, thanks

**Comment by sick13** [comment]
yeap that's it, also to add further info. i did not touch the setting's what so ever (anything i need to do there maybe?)

**Comment by linuxgurugamer** [comment]
Fixed, thanks
