### ISSUE TITLE
Unable to select craft in editor

### ISSUE THREAD

**Issue by gamerscircle** [linuxgurugamer/EditorExtensionsRedux#2]
After I use the "root" tool and change root, I am not able to select the craft that is currently in the editor.  If I exit out of the editor and re-enter.  I am able to load up the craft, the root has been changed and I can not manipulate the craft.

If I go to change the root, the same happens as above.

**Comment by linuxgurugamer** [comment]
Oops, I let a dev version out the door.
This fixes that:  https://www.dropbox.com/s/3gy49plks1zzcom/EditorExtensionsRedux-3.2.1.3.zip?dl=0
