### ISSUE TITLE
Entering text into Text Fields in the Editor triggers Hotkeys

### ISSUE THREAD

**Issue by Poodmund** [linuxgurugamer/EditorExtensionsRedux#28]
When I am entering text into a text field in the Editor scene, either in the Vessel Name input or in the Part Search input, the hot keys are activated. 

Is there anyway to detect when these text field inputs are active and disable the hotkeys temporarily so that they are not triggered when the user is typing into these fields?

**Comment by linuxgurugamer** [comment]
Thinking about it, this might be done as a small, separate mod.

**Comment by linuxgurugamer** [comment]
Fixed in next release
