### ISSUE TITLE
Exception when No offset limit is checked

### ISSUE THREAD

**Issue by jarosm** [linuxgurugamer/EditorExtensionsRedux#29]
KSP 1.3.1, EXR 3.3.15

When No offset limit is on, then there is following exception:
`NullReferenceException: Object reference not set to an instance of an object at EditorExtensionsRedux.NoOffsetBehaviour.FreeOffsetBehaviour.Start ()`

Tested on a clean install.

**Comment by linuxgurugamer** [comment]
Some questions:
1.  Does it happen every time, or only the first?
2.  What OS are you running on?
3.  Does it appear to affect the functionality?
4.  Does it happen when you select a part?  If not, when?
5.  What part?

also, a log file would be helpful.

thanks

**Comment by jarosm** [comment]
ad 1. Everytime VAB/SPH is entered or No offset limit is enabled (through settings or L key).
ad 2. Windows 8.1 x64
ad 3. No limit offset is completly disabled. It's impossible to move a part over the offset limit.
ad 4. It happens with or without parts in the working area (see answer no. 1)

[https://www.dropbox.com/s/4ulciwhnkl3bt8s/KSP.zip?dl=0](url)

In the log are instances of the exception when VAB was entered and when checkbox was switched off and then on.

**Comment by linuxgurugamer** [comment]
Ok, I'll look into it
thanks for the update

**Comment by linuxgurugamer** [comment]
I found the problem, will be fixed in the next release
Thank you
