### ISSUE TITLE
Minor pet peeve: typing in the search box is interpreted as a control

### ISSUE THREAD

**Issue by Kerbas-ad-astra** [linuxgurugamer/EditorExtensionsRedux#3]
E.g. typing things with "c"s causes the snap angle to increase.

**Comment by linuxgurugamer** [comment]
yeech!  That's a bug in the game, it passing the keystrokes through to the mods.

I don't know how to work around it, but I'll ask

**Comment by linuxgurugamer** [comment]
Problem solved, watch for an update later today or tonite (US east coast)
