### ISSUE TITLE
Symmetry/angle snap hotkeys sometimes aren't restored on exit

### ISSUE THREAD

**Issue by ts826848** [linuxgurugamer/EditorExtensionsRedux#30]
Unfortunately, I haven't been able to get this to reproduce consistently, but I figured I'd open an issue just in case this is a known problem.

This appears to usually happen after quitting KSP using Command-Q directly from the VAB editor, but I'll have to check to make sure it doesn't happen when quitting from other scenes. Unfortunately, this seems to happen only when I have a large number of mods installed, which makes testing this a real pain :(

**Comment by darthgently** [comment]
Saving a game can take more time when memory is low and many mods installed can cause low memory.  If the game is crashed from the editor when saving it can cause this error from what I was reading here.  So maybe you need to allow more time for the file to save before Command-Q?  I'm totally guessing here.  But on my potato machine on larger craft files it can take over half a minute for it to save (from watching file size until it stops growing in the directory itself).  The below is from the forum:
Note in very rare circumstances the symmetry and angle snap keybindings might be lost.  This would only occur   if another mod triggers the game to save its settings while in the VAB/SPH, *and* the game subsequently crashes  or is killed before exiting the building.  If it happens, you can easily restore the keybindings (X and C by  default) by hovering over the toolbar button and selecting the menu option "Reset Mode & Snap keys".

**Comment by linuxgurugamer** [comment]
Fixed in 3.4.5
