### ISSUE TITLE
ksp 1.4.3

### ISSUE THREAD

**Issue by 0142929** [linuxgurugamer/EditorExtensionsRedux#31]
3.3.19.3 not working with ksp 1.4.3,
needs to update please :)

me using ModuleManager.3.0.7.dll

**Comment by Gordon-Dry** [comment]
@0142929 I'm using that version and it works.

**Comment by 0142929** [comment]
![clipboard01](https://user-images.githubusercontent.com/896793/40680146-d2dadb00-638d-11e8-964d-b1fb6efb7a43.jpg)

it is loaded but not working, perhaps something wrong with my ksp 1.4.3 02152

**Comment by 0142929** [comment]
me trying many times with mm 3.0.6, 3.0.7 and single mod only.
EditorExtensionsRedux on ksp win x64 1.4.3 02152
not working

**Comment by linuxgurugamer** [comment]
This is not the correct place for this.
Please post your messages in the forum for help
It does work, there is something wrong with your install, and someone in the forums may be able to help

**Comment by 0142929** [comment]
me reinstalled with clean install without dlc - same.
log spamming with:
[EXC 00:34:15.031] FileNotFoundException: Could not load file or assembly 'ClickThroughBlocker, Version=0.1.3.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
have anybody same problem?

**Comment by 0142929** [comment]
ok, it work now.
installing ClickThroughBlocker helps.
thanks

**Comment by linuxgurugamer** [comment]
Please do NOT use this for support.  That is what the forums are for

**Comment by 0142929** [comment]
oh, me get it.
me realized now, that this topic is not related to EditorExtensionsRedux.
me think, me should look for the developer of the modification and ask to build the dependencies in the archive, or add notifications to the log about the fact that they are not found.
this could be very useful is not it?...

anyway me do not know what forums we are talking about.
by way, as me wrote above, the problem is already solved ...
thanks....
