### ISSUE TITLE
Null Reference Exception when adding new parts in Editor (VAB)

### ISSUE THREAD

**Issue by titanin** [linuxgurugamer/EditorExtensionsRedux#39]
```
​[EXC 15:43:04.813] NullReferenceException
    EditorExtensionsRedux.EditorExtensions.MoveParts ()
    EditorExtensionsRedux.EditorExtensions.Update ()
```

​

**Comment by linuxgurugamer** [comment]
Question, do you have Making History installed?

**Comment by titanin** [comment]
I did not at the time. Since then this occured me once again another time. I then just reinstalled the mod and everything seemed to be working fine. And now I have Making History installed. No quarrels. So its kind of odd behaviour and hard to replicate. Hope that helps.

**Comment by linuxgurugamer** [comment]
A one-time exception is almost impossible to debug, so for now I'll close this.  Feel free to reopen if you get more of them
