### ISSUE TITLE
Symmetry and horizontal/vertical alignment can cause Editor Extensions to stop working

### ISSUE THREAD

**Issue by blowfishpro** [linuxgurugamer/EditorExtensionsRedux#40]
**Steps to Reproduce**
* Surface attach a part with some symmetry
* Align it vertically or horizontally (i.e. press v or h keys while hovering over it)
* While the part is still moving, pick it up (this will cause the symmetry counterparts to be destroyed)

**Observed Behavior**
* Editor Extensions spams NREs and none of its functionality will work until leaving and re-entering the editor
* ```
  [EXC 21:35:34.011] NullReferenceException
  	EditorExtensionsRedux.EditorExtensions.MoveParts ()
  	EditorExtensionsRedux.EditorExtensions.Update ()
  ```

**Comment by linuxgurugamer** [comment]
What do you mean by "part still moving"?
What version of KSP?
Log file, please

**Comment by blowfishpro** [comment]
KSP 1.5.1 (though I've been seeing this issue for several versions now, just didn't manage to figure out when it was happening until now).

Still moving - when you align a part with EE (v or h keys), it slides to the correct location over a few seconds, it's during that time that you can reproduce this.

I can provide my log, but as someone who reads a ton of logs I really don't think it will be that helpful in this case.

My guess is that EE is holding on to a reference to the symmetry counterpart, so when KSP destroys it EE is still trying to update its position, which of course it can't because it no longer exists.

**Comment by linuxgurugamer** [comment]
Oh, I understand now.  I'll see if I can fix it this evening

**Comment by linuxgurugamer** [comment]
Fixed and released.
Thank you
