### ISSUE TITLE
Behavior of center horizontally or vertically function do not always behave as expected.

### ISSUE THREAD

**Issue by Galenmacil** [linuxgurugamer/EditorExtensionsRedux#7]
Mainly using "center horizontally" sometimes does nothing depending on wether a part was already centered around the X or Y axis.

Example: Suppose X is left/right, Y is forward/back and Z is up/down (from default view point). If, using 90 degree angle snap, you align a part on top of another one on the X axis but not on the Y axis, using center horizontally does nothing. It is as if the mod assume horizontal to always be the X axis and never the Y axis.

**Comment by linuxgurugamer** [comment]
Actually, it can do both, you just need to use it properly.  I'll have to update the docs.
You hold down (on Windows) the Left Shift and hit the H.  Specifically the editor FineTweak key
