### ISSUE TITLE
Fine Adjustment do not respect "Relative" editor coordinate mode.

### ISSUE THREAD

**Issue by Galenmacil** [linuxgurugamer/EditorExtensionsRedux#9]
Fine adjustment always behave in "Abolute" mode making it impossible to fine offset rotated parts...

**Comment by linuxgurugamer** [comment]
Example, please

**Comment by Galenmacil** [comment]
In the editor (VAB or SPH) the translate and rotate tool can be used in two different mode.

1 - **_Absolute mode_**: In this mode, the part's "parent" rotation is not taken into account.

2- **_Relative mode_**: In this mode, the part's "parent" rotation is taken into account.  If you have a part that is attached at a 90 degree angle to it's parent part, this mode behave exactly as the absolute mode.

Suppose we have this scenario: You want to place a control surface on a vertical stabilizer that is angled 45 degree or so (think modern military fighter like an F-22 vertical stabilizer or on the venerable F-18). You snap the control surface to the edge of the stabilizer but later want to slide it a bit along the edge of said stabilizer. To do this, you need to use the **translation tool in relative mode** to respect the "parent" part 45 degree angle otherwise, in absolute mode, any movement of the control surface will result in it moving away from it's parent... By default, the key to toggle between mode is 'E'.

So, in fine adjustment mode, translation and rotation are always performed as if in the absolute mode which pose problem when you attempt to fine adjust a part like in the example above.

I did my best to describe a good example but if you are in doubt, try it in the editor...

**Comment by linuxgurugamer** [comment]
Fixed in latest release
